services:
  - type: web
    name: PORTFOLIO2
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn projectname.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: projectname.settings
      - key: SECRET_KEY
        generateValue: true
